//
//  HomeModels.swift
//  Car_Clean_Swift
//
//  Created by Alvaro Vinicius do Nascimento Fernandes on 12/12/19.
//  Copyright (c) 2019 Alvaro Vinicius do Nascimento Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    
    enum Car: String, CaseIterable {
        case esportivos, luxo, classicos
    }
    
    enum CarModels {
        
        struct Response: Codable {
            var carros: Carros?
        }
        
        class Carros: Codable{
            var carro: [Carro]?
            
            init(carro: [Carro]?) {
                self.carro = carro
            }
        }
        
        class Carro: Codable//, Equatable
        {
            //        static func == (lhs: TableCarModels.Carro, rhs: TableCarModels.Carro) -> Bool {
            //            ==
            //        }
            
            var nome: String
            var desc: String
            var url_info: String?
            var url_foto: String?
            var url_video: String?
            var latitude: String?
            var longitude: String?
            
            init(nome: String, desc: String) {
                self.nome = nome
                self.desc = desc
            }
        }
    }

}


