//
//  HomePresenter.swift
//  Car_Clean_Swift
//
//  Created by Alvaro Vinicius do Nascimento Fernandes on 12/12/19.
//  Copyright (c) 2019 Alvaro Vinicius do Nascimento Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol HomePresentationLogic {
    func reloadCollection()
    func presentRequestFailureAlert()
}

class HomePresenter: HomePresentationLogic {
    
    weak var viewController: HomeDisplayLogic?
    
    func reloadCollection() {
        viewController?.reloadCollection()
    }
    
    func presentRequestFailureAlert() {
        let title  = "We had a connection problem"
        let message  = "Check your internet connection"
        viewController?.presentRequestFailureAlert(title, message)
    }

}
