//
//  HomeWorker.swift
//  Car_Clean_Swift
//
//  Created by Alvaro Vinicius do Nascimento Fernandes on 12/12/19.
//  Copyright (c) 2019 Alvaro Vinicius do Nascimento Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import Foundation
import PromiseKit

class HomeWorker {

    let networkProvider: NetworkProvider
    
    init(networkProvider: NetworkProvider = NetworkProvider()) {
        self.networkProvider = networkProvider
    }
    
    func getCarList(car: Home.Car) -> Promise<Home.CarModels.Response> {
        let requestProvider = HomeProvider(car: car)
        return networkProvider.execute(request: requestProvider, parser: Home.CarModels.Response.self)
    }
    
}
